### ISSUE TITLE
Special Characters within operation/service names

### ISSUE THREAD

**Issue by katholen** [ExpediaDotCom/haystack#325]
We have clients that are looking to use Spaces, periods, and curly braces within the operation names of spans. The same problem could apply to service names as well. With traces there is no problem, but there is a problem when using metrictank as it has special character restrictions. The current implementation is to encode a character with a string of characters. i.e: '.' => "___" and ' ' => "---"

However, this is going to get messy longterm as new characters are found to be an issue in various components. 

PRs this affects:
- https://github.com/ExpediaDotCom/haystack-ui/pull/212
- https://github.com/ExpediaDotCom/haystack-commons/pull/8

**Comment by ayansen** [comment]
As you rightly said, it would be a problem manually encoding each special character might not be a good idea in the long run, I think it makes sense to base64 encode the serviceName and operationName but that would mean we loose the ability to search for these metrics using an open-source ui like grafana. This can definitely live behind a flag, which decides either we discard messages with such characters or else base64 encode it.  however the same flag should be honoured by the ui. I'd like to decouple the two if possible. any suggestions are welcome

**Comment by katholen** [comment]
I think that is the weird thing about this is that anyway we decode/encode it both the UI and services would need to be configured/coded the same way to handle this. 

++ @eleduardo

**Comment by vsen** [comment]
Floating couple of more ideas -
- replace special chars with __hex-code-for-char__ 
-  Apply URI encoding/decoding(eg. encodeUriComponent) on operation and service names might also work, since the issue is mainly with querying from metrictank, and not with storing there
