### ISSUE TITLE
Spans without an error tagged are marked as neither successful nor failure

### ISSUE THREAD

**Issue by katholen** [ExpediaDotCom/haystack#326]
Not sure if this is a feature or a an issue, so opening this up to start the dialog.

I notice that in the event if there is no span tag with error the success metrics are not calculated. There is a test that asserts that nothing happens in this case. Should the default behavior be to mark it as a success, and only mark it as a failure if the error tag is present? I ask because the total count would still include those that were neither marked as success/failure, but would not be displayed within the view

**Comment by katholen** [comment]
It is also only allowed to be a boolean. We initially tried to integrate with a boolean string and it was ignored. Should we allow strings as well in this field?

**Comment by shellbj** [comment]
No, to allowing strings.  Follow the [specification](https://github.com/opentracing/specification/blob/master/semantic_conventions.md).

```
error | bool | true if and only if the application considers the operation represented by the Span to have failed
```

If you want something more detailed, then a log field (also in the specification) is where that would go.

**Comment by katholen** [comment]
In terms of the strings that is fine with me. There are two aspects to the issue for us, one was in a client library that was created (resolved) and another appears to be somewhere in our pipeline into Haystack which maybe out of our control. We will need to track down the issue and follow up.

**Comment by ayansen** [comment]
We did have a discussion around it initially and had decided that with the error tag missing would mean we don't really know about the status of the span and hence marking it as success might be incorrect and hence we opted to not trend it. Can you elaborate on the issue a little more ? the total count trend should still be rendered in the ui.

**Comment by katholen** [comment]
The issue originated, because the client library we were using didn't always set the error tag. Once that was set we found that there is a conversion happening in our pipeline converting it from boolean to string. As a result, in the first instance no successes were showing up and in the second case no errors were showing up. 

What you suggest makes sense, but it was odd seeing totals that did not match the sum of the number of success/failure requests (specifically in this case where both were zero). Maybe if there is a third state do you think it makes sense to be able to visualize that in the ui as an unknown line?

**Comment by shellbj** [comment]
You could use a log event for `error.kind` (maybe `message`?) to capture your ambiguous failures (a `maybe` state for a bool???). Trending those wouldn't be built in however.

Is it possible to fix up your traces after the fact and remove the bool->string conversion?  That would give you the best outcomes.

**Comment by katholen** [comment]
Ya we fixed it on our end (by creating a custom build of trends), there are three upstream services converting it to a string, so it will take some work to make it correct. One of those is the jaeger-zipkin library. Given we are tied to jaeger-zipkin right now, I think it is something we will live with on our end until we change that. So, I am personally fine with the "follow the specs" resolution, just need to be clear that all transformers within trends require the correct type.

In terms of the error.kind, I am not sure if we gain a whole lot. I was really looking at should we trend on ambiguous statuses instead of just success and failure? If ambiguous status is valid, then I think we should give visibility to those metric points, which should allow them to identify why they are ambiguous.

**Comment by shellbj** [comment]
> I was really looking at should we trend on ambiguous statuses instead of just success and failure? If ambiguous status is valid, then I think we should give visibility to those metric points, which should allow them to identify why they are ambiguous.

I like this idea; even it doesn't fit our data set, it has obvious utility.

**Comment by katholen** [comment]
If you guys agree with it I can have the pr out tomorrowish.

**Comment by kapilra** [comment]
Idea of creating a trend for ambiguous statuses looks good to me. I think should go ahead and raise a PR 👍 

Here is a high level list of items that would need to be updated for this change:
- [span-timeseries-transformer](https://github.com/ExpediaDotCom/haystack-trends/tree/master/span-timeseries-transformer): add a new transformer
- [timeseries-aggregator](https://github.com/ExpediaDotCom/haystack-trends/tree/master/timeseries-aggregator): add a rule for this new trend
- [haystack-ui](https://github.com/ExpediaDotCom/haystack-ui): to display this new trend on UI
- and the last item is [documentation](https://github.com/ExpediaDotCom/haystack/tree/master/docs)  :)

**Comment by katholen** [comment]
@kapilra would I need to create a new transformer or could I just use the existing status transformer? We are already doing the work there to filter out the ambiguous results so it would be easier/cleaner since we want the aggregates to be part of the status trends

**Comment by kapilra** [comment]
@katholen yes, what you are saying is right. My bad!

**Comment by katholen** [comment]
@kapilra -> Haha no worries just wanted to make sure we were talking the same thing before I made the changes. Working on the changes now, have to setup some infra on our end to automate deploying in our environment should have the changes up before the end of the week.

**Comment by baharclerode** [comment]
This has created really strange behavior in the trends UI, where many services that do not set the `error` tag on their successful spans now show in the UI as having 0 successful spans, so many operations now appear to be failing when they aren't.

I think to be consistent with the OpenTracing spec, all of the spans that Haystack considers "ambiguous" need to be treated as successful anywhere that matters-- It states that `error` is

> `true` if and only if the application considers the operation represented by the Span to have failed

which would also mean that any non-`true` value of the tag (including omission of the tag altogether) must mean that the application considers the operation represented by the Span to not have failed.

**Comment by kapilra** [comment]
@baharclerode I like the idea of marking "ambiguous" more than considering such spans as success. Reason being, I'll not consider ambiguous as failure, but unknown in the service graph. Its kind of misinterpretation IMO to consider spans without `error` tag as success. We don't really know whether they missed it or intentionally left it to signify a success. Consider a case where a service missed `error` tag and sees 100% success always.

By having "ambiguous" spans and success / failure being an important part of any tracing system, there is no chance of misinterpretation.

**Comment by baharclerode** [comment]
> Consider a case where a service missed error tag and sees 100% success always.

Yes, but that service is by definition _not_ OpenTracing-compliant (and if it purports to be compliant, then that's a bug in the service that should be fixed). Is the intention to cater to non-OpenTracing services at the expense of OpenTracing services?

> We don't really know whether they missed it or intentionally left it to signify a success.

The "if and only if" language in the spec is not something that people generally slip into conversation without care or otherwise misuse, and it has a very definite meaning; I don't think there's much room for misinterpretation. If you have `error=true`, you intend it to be a failure, and if you do not have `error=true`, you intend it to be a success.

The main concern is that as a user of the UI, "ambiguous" is meaningless by the time it bubbles up there, and mostly results in confusing graphs where applications are very much operating successfully, but haystack is reporting 0% success. It's not a very good user experience, especially from a non-technical user perspective whom are neither familiar with the applications in question, nor the OpenTracing spec.

**Comment by katholen** [comment]
I would add to @baharclerode -s comment that if there is value in an ambiguous state that the current UI visualization could be changed in order to make this more intuitive. It is currently in a proposal state and is not finalized.

**Comment by eleduardo** [comment]
I would like to second @baharclerode and @mchandramouli call out... if the tag is missing it should be considered success... I am actually looking at the opentracing-contrib and a lot of the instrumentation there is not setting the success tag only setting it up on failure... My guess is that a lot of OSS instrumentation would follow this pattern.

**Comment by katholen** [comment]
Closing out as the PR was merged. Resolution:
- A span is an error if and only if the error tag is true
