### ISSUE TITLE
suggest you tag this repo with distributed-tracing

### ISSUE THREAD

**Issue by adriancole** [ExpediaDotCom/haystack#474]
The de-facto tag for distributed tracing is "distributed-tracing" This repo is too important to go un-noticed! https://github.com/topics/distributed-tracing

Cheers,
-A

**Comment by vsen** [comment]
Thanks for the suggestion @adriancole, will add 🙂

**Comment by ashishagg** [comment]
We have added "distributed-tracing" tag to our repos. Thanks again!

I am closing this issue.
