### ISSUE TITLE
[Feature Request] Haystack should alert in case there is an anomaly in any of the trends it computes

### ISSUE THREAD

**Issue by ayansen** [ExpediaDotCom/haystack#550]
Haystack currently computes trends(aggregates) on certain slicing parameters  on the incoming spans. We currently push those aggregated metrics to metrictank for persistence and show it in the trends view in the haystack ui.It would be nice to understand the patterns of the trends and raise alerts in case of anomalies

**Comment by ayansen** [comment]
Detailing the design proposal for the feature in this wiki - https://github.com/ExpediaDotCom/haystack/wiki/Haystack-Alerts

**Comment by shreyaa-sharma** [comment]
Done.
