### ISSUE TITLE
Haystack: Provision for http ingestion 

### ISSUE THREAD

**Issue by mchandramouli** [ExpediaDotCom/haystack#576]
Haystack has direct kafka ingestion of protobuf spans and a collector to ingest data from Kinesis. Can you provide a  http collector to post spans in protobuf format? Or a grpc collector?

**Comment by ashishagg** [comment]
The good news is that we now support a http span collector.
For more details, read the documentation [here](https://github.com/ExpediaDotCom/haystack-collector/blob/master/http/README.md)

Following PRs fix the issue:
https://github.com/ExpediaDotCom/haystack-collector/pull/47
https://github.com/ExpediaDotCom/haystack-collector/pull/51
