### ISSUE TITLE
[Feature Request] Use default datacenter tag when missing from child spans

### ISSUE THREAD

**Issue by worldtiki** [ExpediaDotCom/haystack#592]
The latency cost uses the datacenter tags to display cross datacenter calls and to calculate network time between datacenters.
Currently this tag needs to be present in both spans that represent each network call and if missing it just displays the datacenter as unknown (N/A).

Example:

> 1. [APP1] root span ----------------------------->
> 2. [APP1]     child span client ------------->
> 3. [APP2]        child span server  ------>

Currently the latency cost requires both spans 2 and 3 to have the datacenter tag.

My proposal is that the latency cost should default to the datacenter tag of the server span for all of the client spans for that service.
In the example above, we would only need to set the datacenter tag in span 1, and all child spans for that service (span 2) would default to that if the tag was missing.

This makes integration with frameworks like Spring Cloud Sleuth easier as we can just set this tag once (using a Filter, ...) and not have to worry about writing extra code to do the same for each of the clients.

**Comment by ashishagg** [comment]
The following PR fixes the issue 
ExpediaDotCom/haystack-traces#186

**Comment by ashishagg** [comment]
Closing the issue. We are going to release haystack-traces by tomorrow.
