### ISSUE TITLE
[ISSUE] add to getting-started documentation how to increase minikube resources if not starting for first time

### ISSUE THREAD

**Issue by mattcallanan** [ExpediaDotCom/haystack#614]
In https://expediadotcom.github.io/haystack/docs/about/getting_started.html, after the following instructions:

> Start Minikube, optionally increasing its memory and/or CPUs if necessary:
> `minikube start --memory 8192 --cpus 4`

Add the following:

> NOTE: if minikube has been previously started without these resource parameters, you may need to convince it to forget it's previous settings.  You can use one of the following 2 methods:
> 1. Stop minikube (`minikube stop`), manually change the memory and cpu settings in your Virtual Machine software, then restart minikube (`minikube start`)
> 2. Delete minikube (with `minikube stop ; minikube delete`) before re-running the above `minikube start ...` instruction
> 
> For more details, see: https://github.com/kubernetes/minikube/issues/567#issuecomment-283992897

**Comment by shreyaa-sharma** [comment]
We have to enhance the UI documentation for this. @keshavpeswani will get this done by end of the day.
