### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by davielin76** [ExpediaDotCom/haystack#621]
Service dependency graph doesn't detect an edge if the duration of the client span exceeds 5 seconds.  Could this time out extend beyond 5 seconds?

**Comment by ashishagg** [comment]
We find a potential race condition in node finder where a span(with longer duration) are missed from edge detection. We have fixed it in [service-graph PR#82](https://github.com/ExpediaDotCom/haystack-service-graph/pull/82).

Please note that service graph on haystack UI still shows the edges seen in last 1 hour, it is configurable though. I am closing this issue for now.
