### ISSUE TITLE
[Haystack Client Java]Performance benchmarking of haystack java tracing client

### ISSUE THREAD

**Issue by ayansen** [ExpediaDotCom/haystack#675]
We are currently blind when it comes to the overhead of tracing in the java client. We come up with a way to measure the performance and computational overhead of the tracing client so that it can be compared against future development and clients in other languages/integrations

**Comment by ayansen** [comment]
We need to benchmark the following information 
1. Tracing with no dispatcher
2. Tracing with Remote grpc dispatcher with protobuf encoding
3. Tracing with Remote http dispatcher with protobuf encoding

**Comment by mchandramouli** [comment]
@ashishagg @nsahai8  Looks like this has been addressed. If so can we document and close this with the `Id injector` documentation?

**Comment by shreyaa-sharma** [comment]
@nsahai8 @doctorXWrites: Can you guys take this up. I have made a card in our trello for the same to follow up. So closing this.
