### ISSUE TITLE
[Feature Request] [Haystack-Traces] Support multiple databases behind a storage backend

### ISSUE THREAD

**Issue by ayansen** [ExpediaDotCom/haystack#687]
The Storage backend implementation currently supports a single database cluster for storing and retrieving spans. It would be useful for a single storage backend instance to be able to talk to multiple databases of the same type for storing and retrieving spans in a round robin fashion. This would help us scale the database by adding a new cluster instead of having to increase the capacity of the cluster.

**Comment by shreyaa-sharma** [comment]
Done. @ayansen: closing this as the readme completion is part of another issue.
