### ISSUE TITLE
[Haystack Client Java] Improve the trace/span id generation time.

### ISSUE THREAD

**Issue by doctorXWrites** [ExpediaDotCom/haystack#705]
Currently the performance of haystack client is approx. 4 times less than jaegar in terms of throughput https://github.com/gsoria/opentracing-java-benchmark.

Cause:
Upon investigation this was mainly attributed to the UUID generation for trace and span id's while creating the context. 

Possible Fix:
Make TraceId be generated by an external function which can be passed by clients. We will provide two default implementations with one using Long random number generator and the other using the current random UUID generator.
Also make span id to always use Long or maybe use the same external function used for trace id for this also.

**Comment by ashishagg** [comment]
Thanks for working on this @doctorXWrites and @keshavpeswani .
Letting consumers define their own generators and providing a sensible default will be a good approach.

**Comment by nsahai8** [comment]
In release [0.2.8](https://github.com/ExpediaDotCom/haystack-client-java/tree/0.2.8), have added the implementation in the client, enabling the consumers to add their own generators. Also, have added three default generators that could be used and we also have benchmarked the results using each of them. Consumers now can also check the results, the steps for that are added in  README.md .

**Comment by nsahai8** [comment]
In release 0.2.8, have added the implementation in the client, enabling the consumers to add their own generators. Also, have added three default generators that could be used and we also have benchmarked the results using each of them. Consumers now can also check the results, the steps for that are added in README.md .
