### ISSUE TITLE
Ability to lift Zipkin tracing data into Haystack

### ISSUE THREAD

**Issue by mitulsharma** [ExpediaDotCom/haystack#717]
There is a need for an adapter which can ingest Zipkin format in existing Haystack infra as migrating from Zipkin to Haystack will be a daunting task for anyone and also people may want to go back.

**Comment by worldtiki** [comment]
Hi @mitulsharma!

I saw you already forked the Pitchfork repo so this is probably not new, but you can use [Pitchfork](https://hotelsdotcom.github.io/pitchfork/) to ingest Zipkin data into Haystack.
