### ISSUE TITLE
Link to AWS Deployment Wiki is Broken

### ISSUE THREAD

**Issue by stepansubbotin** [ExpediaDotCom/haystack#751]
Hello, the link under "AWS Cluster" in the deployment readme ([https://github.com/ExpediaDotCom/haystack/blob/master/deployment/README.md](https://github.com/ExpediaDotCom/haystack/blob/master/deployment/README.md)) seems to be broken. 

Broken link: https://expediadotcom.github.io/haystack/docs/deployment.html 

Could anyone point me to where this is meant to be linking?

**Comment by stepansubbotin** [comment]
I found the proper link and updated the readme. Here's the PR: [https://github.com/ExpediaDotCom/haystack/pull/752](https://github.com/ExpediaDotCom/haystack/pull/752)

**Comment by kapilra** [comment]
Thanks @stepansubbotin !
